challenge_index:
    path:     /
    defaults: { _controller: "GameBundle:Challenge:index" }
    methods:  GET

challenge_show:
    path:     /{id}/show
    defaults: { _controller: "GameBundle:Challenge:show" }
    methods:  GET

challenge_new:
    path:     /new
    defaults: { _controller: "GameBundle:Challenge:new" }
    methods:  [GET, POST]

challenge_edit:
    path:     /{id}/edit
    defaults: { _controller: "GameBundle:Challenge:edit" }
    methods:  [GET, POST]

challenge_delete:
    path:     /{id}/delete
    defaults: { _controller: "GameBundle:Challenge:delete" }
    methods:  DELETE

challenge_add_image_meneur:
    path:     /{id}/add-image-meneur
    defaults: { _controller: "GameBundle:Challenge:addImageMeneur" }
    methods:  [GET, POST]

challenge_private_inscription:
    path:   /{id}/inscription_private_challenge
    defaults: { _controller: GameBundle:Challenge:inscriptionChallenge }
    methods:  [GET, POST]

challenge_public_inscription:
    path:     /{id}/inscription-challenge
    defaults: { _controller: "GameBundle:Challenge:challengePublicInscription" }
    methods:  [GET]

challenge_desinscription:
    path:     /{id}/desinscription-challenge
    defaults: { _controller: "GameBundle:Challenge:challengeDesinscription" }
    methods:  [GET]

challenge_en_cours:
    path:     /challenge-en-cours
    defaults: { _controller: "GameBundle:Challenge:challengeEnCours" }
    methods:  [GET]

challenge_passe:
    path:     /{id}/passe-challenge
    defaults: { _controller: "GameBundle:Challenge:challengeMeneurPasse" }
    methods:  [GET]