challenge_index:
    path:     /
    defaults: { _controller: "GameBundle:Challenge:index" }
    methods:  GET

challenge_show:
    path:     /{id}/show
    defaults: { _controller: "GameBundle:Challenge:show" }
    methods:  GET

challenge_new:
    path:     /new
    defaults: { _controller: "GameBundle:Challenge:new" }
    methods:  [GET, POST]

challenge_edit:
    path:     /{id}/edit
    defaults: { _controller: "GameBundle:Challenge:edit" }
    methods:  [GET, POST]

challenge_delete:
    path:     /{id}/delete
    defaults: { _controller: "GameBundle:Challenge:delete" }
    methods:  DELETE

challenge_add_image_meneur:
    path:     /{id}/add_image_meneur
    defaults: { _controller: "GameBundle:Challenge:add_image_meneur" }
    methods:  [GET, POST]