<?php

namespace UserBundle\Repository;

/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findUserNotCreateur($createur_id)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.id <> :user')
            ->setParameter('user', $createur_id)
            ->getQuery();

        return $qb->getResult();
    }

    public function findUserInGroupNotMeneur($challenge)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->leftJoin('GameBundle:Challenge', 'c' )


            ->andWhere('u.id != :user')
            ->setParameter('user', $challenge->getUserMeneur())
            ->getQuery();

        return $qb->getResult();
    }
}
