<?php

namespace UserBundle\Repository;

/**
 * ChallengeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function qfindUserNotCreateur($createur_id)
    {
        $qb = $this->createQueryBuilder('u')
            ->select('u')
            ->where('u.id <> :user')
            ->setParameter('user', $createur_id)
            ->getQuery();

        return $qb->getResult();
    }
}
